// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"

	"github.com/google/uuid"
)

type ArchiveBlockByIdBadRequest ErrorResponse

func (*ArchiveBlockByIdBadRequest) archiveBlockByIdRes() {}

type ArchiveBlockByIdNotFound ErrorResponse

func (*ArchiveBlockByIdNotFound) archiveBlockByIdRes() {}

type ArchiveBlockByIdUnauthorized ErrorResponse

func (*ArchiveBlockByIdUnauthorized) archiveBlockByIdRes() {}

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/Block
type Block struct {
	ID            uuid.UUID      `json:"id"`
	CreatedAt     time.Time      `json:"created_at"`
	ArchivedAt    OptNilDateTime `json:"archived_at"`
	Days          []DayEntry     `json:"days"`
	ShoppingItems []ShoppingItem `json:"shopping_items"`
}

// GetID returns the value of ID.
func (s *Block) GetID() uuid.UUID {
	return s.ID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Block) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetArchivedAt returns the value of ArchivedAt.
func (s *Block) GetArchivedAt() OptNilDateTime {
	return s.ArchivedAt
}

// GetDays returns the value of Days.
func (s *Block) GetDays() []DayEntry {
	return s.Days
}

// GetShoppingItems returns the value of ShoppingItems.
func (s *Block) GetShoppingItems() []ShoppingItem {
	return s.ShoppingItems
}

// SetID sets the value of ID.
func (s *Block) SetID(val uuid.UUID) {
	s.ID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Block) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetArchivedAt sets the value of ArchivedAt.
func (s *Block) SetArchivedAt(val OptNilDateTime) {
	s.ArchivedAt = val
}

// SetDays sets the value of Days.
func (s *Block) SetDays(val []DayEntry) {
	s.Days = val
}

// SetShoppingItems sets the value of ShoppingItems.
func (s *Block) SetShoppingItems(val []ShoppingItem) {
	s.ShoppingItems = val
}

func (*Block) archiveBlockByIdRes() {}
func (*Block) createBlockRes()      {}
func (*Block) getBlockRes()         {}
func (*Block) getCurrentBlockRes()  {}
func (*Block) unarchiveBlockRes()   {}

// Ref: #/components/schemas/BlockSummary
type BlockSummary struct {
	ID         uuid.UUID      `json:"id"`
	CreatedAt  time.Time      `json:"created_at"`
	ArchivedAt OptNilDateTime `json:"archived_at"`
}

// GetID returns the value of ID.
func (s *BlockSummary) GetID() uuid.UUID {
	return s.ID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *BlockSummary) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetArchivedAt returns the value of ArchivedAt.
func (s *BlockSummary) GetArchivedAt() OptNilDateTime {
	return s.ArchivedAt
}

// SetID sets the value of ID.
func (s *BlockSummary) SetID(val uuid.UUID) {
	s.ID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *BlockSummary) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetArchivedAt sets the value of ArchivedAt.
func (s *BlockSummary) SetArchivedAt(val OptNilDateTime) {
	s.ArchivedAt = val
}

type CreateDayBadRequest ErrorResponse

func (*CreateDayBadRequest) createDayRes() {}

// Ref: #/components/schemas/CreateDayRequest
type CreateDayRequest struct {
	BlockID uuid.UUID `json:"block_id"`
	Date    time.Time `json:"date"`
}

// GetBlockID returns the value of BlockID.
func (s *CreateDayRequest) GetBlockID() uuid.UUID {
	return s.BlockID
}

// GetDate returns the value of Date.
func (s *CreateDayRequest) GetDate() time.Time {
	return s.Date
}

// SetBlockID sets the value of BlockID.
func (s *CreateDayRequest) SetBlockID(val uuid.UUID) {
	s.BlockID = val
}

// SetDate sets the value of Date.
func (s *CreateDayRequest) SetDate(val time.Time) {
	s.Date = val
}

type CreateDayUnauthorized ErrorResponse

func (*CreateDayUnauthorized) createDayRes() {}

type CreateShoppingItemBadRequest ErrorResponse

func (*CreateShoppingItemBadRequest) createShoppingItemRes() {}

// Ref: #/components/schemas/CreateShoppingItemRequest
type CreateShoppingItemRequest struct {
	BlockID uuid.UUID `json:"block_id"`
	Name    string    `json:"name"`
}

// GetBlockID returns the value of BlockID.
func (s *CreateShoppingItemRequest) GetBlockID() uuid.UUID {
	return s.BlockID
}

// GetName returns the value of Name.
func (s *CreateShoppingItemRequest) GetName() string {
	return s.Name
}

// SetBlockID sets the value of BlockID.
func (s *CreateShoppingItemRequest) SetBlockID(val uuid.UUID) {
	s.BlockID = val
}

// SetName sets the value of Name.
func (s *CreateShoppingItemRequest) SetName(val string) {
	s.Name = val
}

type CreateShoppingItemUnauthorized ErrorResponse

func (*CreateShoppingItemUnauthorized) createShoppingItemRes() {}

// Ref: #/components/schemas/DayEntry
type DayEntry struct {
	ID      uuid.UUID    `json:"id"`
	BlockID uuid.UUID    `json:"block_id"`
	Date    time.Time    `json:"date"`
	Note    OptNilString `json:"note"`
	Lunch   OptNilString `json:"lunch"`
	Dinner  OptNilString `json:"dinner"`
}

// GetID returns the value of ID.
func (s *DayEntry) GetID() uuid.UUID {
	return s.ID
}

// GetBlockID returns the value of BlockID.
func (s *DayEntry) GetBlockID() uuid.UUID {
	return s.BlockID
}

// GetDate returns the value of Date.
func (s *DayEntry) GetDate() time.Time {
	return s.Date
}

// GetNote returns the value of Note.
func (s *DayEntry) GetNote() OptNilString {
	return s.Note
}

// GetLunch returns the value of Lunch.
func (s *DayEntry) GetLunch() OptNilString {
	return s.Lunch
}

// GetDinner returns the value of Dinner.
func (s *DayEntry) GetDinner() OptNilString {
	return s.Dinner
}

// SetID sets the value of ID.
func (s *DayEntry) SetID(val uuid.UUID) {
	s.ID = val
}

// SetBlockID sets the value of BlockID.
func (s *DayEntry) SetBlockID(val uuid.UUID) {
	s.BlockID = val
}

// SetDate sets the value of Date.
func (s *DayEntry) SetDate(val time.Time) {
	s.Date = val
}

// SetNote sets the value of Note.
func (s *DayEntry) SetNote(val OptNilString) {
	s.Note = val
}

// SetLunch sets the value of Lunch.
func (s *DayEntry) SetLunch(val OptNilString) {
	s.Lunch = val
}

// SetDinner sets the value of Dinner.
func (s *DayEntry) SetDinner(val OptNilString) {
	s.Dinner = val
}

func (*DayEntry) createDayRes() {}
func (*DayEntry) updateDayRes() {}

type DeleteBlockBadRequest ErrorResponse

func (*DeleteBlockBadRequest) deleteBlockRes() {}

// DeleteBlockNoContent is response for DeleteBlock operation.
type DeleteBlockNoContent struct{}

func (*DeleteBlockNoContent) deleteBlockRes() {}

type DeleteBlockNotFound ErrorResponse

func (*DeleteBlockNotFound) deleteBlockRes() {}

type DeleteBlockUnauthorized ErrorResponse

func (*DeleteBlockUnauthorized) deleteBlockRes() {}

// DeleteDayNoContent is response for DeleteDay operation.
type DeleteDayNoContent struct{}

func (*DeleteDayNoContent) deleteDayRes() {}

type DeleteDayNotFound ErrorResponse

func (*DeleteDayNotFound) deleteDayRes() {}

type DeleteDayUnauthorized ErrorResponse

func (*DeleteDayUnauthorized) deleteDayRes() {}

// DeleteShoppingItemNoContent is response for DeleteShoppingItem operation.
type DeleteShoppingItemNoContent struct{}

func (*DeleteShoppingItemNoContent) deleteShoppingItemRes() {}

type DeleteShoppingItemNotFound ErrorResponse

func (*DeleteShoppingItemNotFound) deleteShoppingItemRes() {}

type DeleteShoppingItemUnauthorized ErrorResponse

func (*DeleteShoppingItemUnauthorized) deleteShoppingItemRes() {}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *ErrorResponse) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *ErrorResponse) SetMessage(val string) {
	s.Message = val
}

func (*ErrorResponse) createBlockRes()          {}
func (*ErrorResponse) getCurrentBlockRes()      {}
func (*ErrorResponse) getUserInfoRes()          {}
func (*ErrorResponse) listBlocksRes()           {}
func (*ErrorResponse) reorderShoppingItemsRes() {}

type GetBlockNotFound ErrorResponse

func (*GetBlockNotFound) getBlockRes() {}

type GetBlockUnauthorized ErrorResponse

func (*GetBlockUnauthorized) getBlockRes() {}

type ListBlocksOKApplicationJSON []BlockSummary

func (*ListBlocksOKApplicationJSON) listBlocksRes() {}

// Ref: #/components/schemas/OIDCConfig
type OIDCConfig struct {
	Enabled  bool         `json:"enabled"`
	Issuer   OptNilString `json:"issuer"`
	ClientID OptNilString `json:"client_id"`
	Audience OptNilString `json:"audience"`
}

// GetEnabled returns the value of Enabled.
func (s *OIDCConfig) GetEnabled() bool {
	return s.Enabled
}

// GetIssuer returns the value of Issuer.
func (s *OIDCConfig) GetIssuer() OptNilString {
	return s.Issuer
}

// GetClientID returns the value of ClientID.
func (s *OIDCConfig) GetClientID() OptNilString {
	return s.ClientID
}

// GetAudience returns the value of Audience.
func (s *OIDCConfig) GetAudience() OptNilString {
	return s.Audience
}

// SetEnabled sets the value of Enabled.
func (s *OIDCConfig) SetEnabled(val bool) {
	s.Enabled = val
}

// SetIssuer sets the value of Issuer.
func (s *OIDCConfig) SetIssuer(val OptNilString) {
	s.Issuer = val
}

// SetClientID sets the value of ClientID.
func (s *OIDCConfig) SetClientID(val OptNilString) {
	s.ClientID = val
}

// SetAudience sets the value of Audience.
func (s *OIDCConfig) SetAudience(val OptNilString) {
	s.Audience = val
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilDateTime returns new OptNilDateTime with value set to v.
func NewOptNilDateTime(v time.Time) OptNilDateTime {
	return OptNilDateTime{
		Value: v,
		Set:   true,
	}
}

// OptNilDateTime is optional nullable time.Time.
type OptNilDateTime struct {
	Value time.Time
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilDateTime was set.
func (o OptNilDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilDateTime) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilDateTime) SetToNull() {
	o.Set = true
	o.Null = true
	var v time.Time
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilDateTime) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// ReorderShoppingItemsNoContent is response for ReorderShoppingItems operation.
type ReorderShoppingItemsNoContent struct{}

func (*ReorderShoppingItemsNoContent) reorderShoppingItemsRes() {}

// Ref: #/components/schemas/ReorderShoppingItemsRequest
type ReorderShoppingItemsRequest struct {
	Ids []uuid.UUID `json:"ids"`
}

// GetIds returns the value of Ids.
func (s *ReorderShoppingItemsRequest) GetIds() []uuid.UUID {
	return s.Ids
}

// SetIds sets the value of Ids.
func (s *ReorderShoppingItemsRequest) SetIds(val []uuid.UUID) {
	s.Ids = val
}

// Ref: #/components/schemas/ShoppingItem
type ShoppingItem struct {
	ID        uuid.UUID    `json:"id"`
	BlockID   uuid.UUID    `json:"block_id"`
	Name      string       `json:"name"`
	Note      OptNilString `json:"note"`
	Checked   bool         `json:"checked"`
	CreatedAt time.Time    `json:"created_at"`
}

// GetID returns the value of ID.
func (s *ShoppingItem) GetID() uuid.UUID {
	return s.ID
}

// GetBlockID returns the value of BlockID.
func (s *ShoppingItem) GetBlockID() uuid.UUID {
	return s.BlockID
}

// GetName returns the value of Name.
func (s *ShoppingItem) GetName() string {
	return s.Name
}

// GetNote returns the value of Note.
func (s *ShoppingItem) GetNote() OptNilString {
	return s.Note
}

// GetChecked returns the value of Checked.
func (s *ShoppingItem) GetChecked() bool {
	return s.Checked
}

// GetCreatedAt returns the value of CreatedAt.
func (s *ShoppingItem) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *ShoppingItem) SetID(val uuid.UUID) {
	s.ID = val
}

// SetBlockID sets the value of BlockID.
func (s *ShoppingItem) SetBlockID(val uuid.UUID) {
	s.BlockID = val
}

// SetName sets the value of Name.
func (s *ShoppingItem) SetName(val string) {
	s.Name = val
}

// SetNote sets the value of Note.
func (s *ShoppingItem) SetNote(val OptNilString) {
	s.Note = val
}

// SetChecked sets the value of Checked.
func (s *ShoppingItem) SetChecked(val bool) {
	s.Checked = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *ShoppingItem) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

func (*ShoppingItem) createShoppingItemRes() {}
func (*ShoppingItem) updateShoppingItemRes() {}

type UnarchiveBlockBadRequest ErrorResponse

func (*UnarchiveBlockBadRequest) unarchiveBlockRes() {}

type UnarchiveBlockNotFound ErrorResponse

func (*UnarchiveBlockNotFound) unarchiveBlockRes() {}

type UnarchiveBlockUnauthorized ErrorResponse

func (*UnarchiveBlockUnauthorized) unarchiveBlockRes() {}

type UpdateDayNotFound ErrorResponse

func (*UpdateDayNotFound) updateDayRes() {}

// Ref: #/components/schemas/UpdateDayRequest
type UpdateDayRequest struct {
	Note   OptNilString `json:"note"`
	Lunch  OptNilString `json:"lunch"`
	Dinner OptNilString `json:"dinner"`
}

// GetNote returns the value of Note.
func (s *UpdateDayRequest) GetNote() OptNilString {
	return s.Note
}

// GetLunch returns the value of Lunch.
func (s *UpdateDayRequest) GetLunch() OptNilString {
	return s.Lunch
}

// GetDinner returns the value of Dinner.
func (s *UpdateDayRequest) GetDinner() OptNilString {
	return s.Dinner
}

// SetNote sets the value of Note.
func (s *UpdateDayRequest) SetNote(val OptNilString) {
	s.Note = val
}

// SetLunch sets the value of Lunch.
func (s *UpdateDayRequest) SetLunch(val OptNilString) {
	s.Lunch = val
}

// SetDinner sets the value of Dinner.
func (s *UpdateDayRequest) SetDinner(val OptNilString) {
	s.Dinner = val
}

type UpdateDayUnauthorized ErrorResponse

func (*UpdateDayUnauthorized) updateDayRes() {}

type UpdateShoppingItemNotFound ErrorResponse

func (*UpdateShoppingItemNotFound) updateShoppingItemRes() {}

// Ref: #/components/schemas/UpdateShoppingItemRequest
type UpdateShoppingItemRequest struct {
	Name    OptString    `json:"name"`
	Checked OptBool      `json:"checked"`
	Note    OptNilString `json:"note"`
}

// GetName returns the value of Name.
func (s *UpdateShoppingItemRequest) GetName() OptString {
	return s.Name
}

// GetChecked returns the value of Checked.
func (s *UpdateShoppingItemRequest) GetChecked() OptBool {
	return s.Checked
}

// GetNote returns the value of Note.
func (s *UpdateShoppingItemRequest) GetNote() OptNilString {
	return s.Note
}

// SetName sets the value of Name.
func (s *UpdateShoppingItemRequest) SetName(val OptString) {
	s.Name = val
}

// SetChecked sets the value of Checked.
func (s *UpdateShoppingItemRequest) SetChecked(val OptBool) {
	s.Checked = val
}

// SetNote sets the value of Note.
func (s *UpdateShoppingItemRequest) SetNote(val OptNilString) {
	s.Note = val
}

type UpdateShoppingItemUnauthorized ErrorResponse

func (*UpdateShoppingItemUnauthorized) updateShoppingItemRes() {}

// Ref: #/components/schemas/UserInfo
type UserInfo struct {
	Sub  string       `json:"sub"`
	Name OptNilString `json:"name"`
}

// GetSub returns the value of Sub.
func (s *UserInfo) GetSub() string {
	return s.Sub
}

// GetName returns the value of Name.
func (s *UserInfo) GetName() OptNilString {
	return s.Name
}

// SetSub sets the value of Sub.
func (s *UserInfo) SetSub(val string) {
	s.Sub = val
}

// SetName sets the value of Name.
func (s *UserInfo) SetName(val OptNilString) {
	s.Name = val
}

func (*UserInfo) getUserInfoRes() {}
