// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	ArchiveBlockByIdOperation     OperationName = "ArchiveBlockById"
	CreateBlockOperation          OperationName = "CreateBlock"
	CreateDayOperation            OperationName = "CreateDay"
	CreateShoppingItemOperation   OperationName = "CreateShoppingItem"
	DeleteBlockOperation          OperationName = "DeleteBlock"
	DeleteDayOperation            OperationName = "DeleteDay"
	DeleteShoppingItemOperation   OperationName = "DeleteShoppingItem"
	GetBlockOperation             OperationName = "GetBlock"
	GetCurrentBlockOperation      OperationName = "GetCurrentBlock"
	GetOIDCConfigOperation        OperationName = "GetOIDCConfig"
	GetUserInfoOperation          OperationName = "GetUserInfo"
	ListBlocksOperation           OperationName = "ListBlocks"
	ReorderShoppingItemsOperation OperationName = "ReorderShoppingItems"
	UnarchiveBlockOperation       OperationName = "UnarchiveBlock"
	UpdateDayOperation            OperationName = "UpdateDay"
	UpdateShoppingItemOperation   OperationName = "UpdateShoppingItem"
)
