// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ArchiveBlockById implements archiveBlockById operation.
//
// 指定ブロックをアーカイブする（未アーカイブの中で最古のブロックのみ可）.
//
// POST /api/blocks/{id}/archive
func (UnimplementedHandler) ArchiveBlockById(ctx context.Context, params ArchiveBlockByIdParams) (r ArchiveBlockByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateBlock implements createBlock operation.
//
// 新しいブロックを作成する（アーカイブなし）.
//
// POST /api/blocks
func (UnimplementedHandler) CreateBlock(ctx context.Context) (r CreateBlockRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateDay implements createDay operation.
//
// 日エントリを追加する.
//
// POST /api/days
func (UnimplementedHandler) CreateDay(ctx context.Context, req *CreateDayRequest) (r CreateDayRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateShoppingItem implements createShoppingItem operation.
//
// 買い物アイテムを追加する.
//
// POST /api/shopping
func (UnimplementedHandler) CreateShoppingItem(ctx context.Context, req *CreateShoppingItemRequest) (r CreateShoppingItemRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteBlock implements deleteBlock operation.
//
// ブロックを削除する（最後に作成された未アーカイブのブロックのみ可）.
//
// DELETE /api/blocks/{id}
func (UnimplementedHandler) DeleteBlock(ctx context.Context, params DeleteBlockParams) (r DeleteBlockRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteDay implements deleteDay operation.
//
// 日エントリを削除する.
//
// DELETE /api/days/{id}
func (UnimplementedHandler) DeleteDay(ctx context.Context, params DeleteDayParams) (r DeleteDayRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteShoppingItem implements deleteShoppingItem operation.
//
// 買い物アイテムを削除する.
//
// DELETE /api/shopping/{id}
func (UnimplementedHandler) DeleteShoppingItem(ctx context.Context, params DeleteShoppingItemParams) (r DeleteShoppingItemRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetBlock implements getBlock operation.
//
// ブロックを取得する.
//
// GET /api/blocks/{id}
func (UnimplementedHandler) GetBlock(ctx context.Context, params GetBlockParams) (r GetBlockRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCurrentBlock implements getCurrentBlock operation.
//
// 現在のブロックを取得する（存在しない場合は自動作成）.
//
// GET /api/blocks/current
func (UnimplementedHandler) GetCurrentBlock(ctx context.Context) (r GetCurrentBlockRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOIDCConfig implements getOIDCConfig operation.
//
// OIDC クライアント設定を取得する（認証不要）.
//
// GET /api/oidc-config
func (UnimplementedHandler) GetOIDCConfig(ctx context.Context) (r *OIDCConfig, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserInfo implements getUserInfo operation.
//
// ログイン中のユーザー情報を取得する.
//
// GET /api/userinfo
func (UnimplementedHandler) GetUserInfo(ctx context.Context) (r GetUserInfoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListBlocks implements listBlocks operation.
//
// ブロック一覧を取得する.
//
// GET /api/blocks
func (UnimplementedHandler) ListBlocks(ctx context.Context) (r ListBlocksRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReorderShoppingItems implements reorderShoppingItems operation.
//
// 買い物アイテムの順序を変更する.
//
// POST /api/shopping/reorder
func (UnimplementedHandler) ReorderShoppingItems(ctx context.Context, req *ReorderShoppingItemsRequest) (r ReorderShoppingItemsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UnarchiveBlock implements unarchiveBlock operation.
//
// 指定ブロックのアーカイブを解除する（アーカイブ済みの中で最新のブロックのみ可）.
//
// POST /api/blocks/{id}/unarchive
func (UnimplementedHandler) UnarchiveBlock(ctx context.Context, params UnarchiveBlockParams) (r UnarchiveBlockRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateDay implements updateDay operation.
//
// 日エントリを更新する.
//
// PUT /api/days/{id}
func (UnimplementedHandler) UpdateDay(ctx context.Context, req *UpdateDayRequest, params UpdateDayParams) (r UpdateDayRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateShoppingItem implements updateShoppingItem operation.
//
// 買い物アイテムを更新する.
//
// PUT /api/shopping/{id}
func (UnimplementedHandler) UpdateShoppingItem(ctx context.Context, req *UpdateShoppingItemRequest, params UpdateShoppingItemParams) (r UpdateShoppingItemRes, _ error) {
	return r, ht.ErrNotImplemented
}
