// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ArchiveBlockById implements archiveBlockById operation.
	//
	// 指定ブロックをアーカイブする（未アーカイブの中で最古のブロックのみ可）.
	//
	// POST /api/blocks/{id}/archive
	ArchiveBlockById(ctx context.Context, params ArchiveBlockByIdParams) (ArchiveBlockByIdRes, error)
	// CreateBlock implements createBlock operation.
	//
	// 新しいブロックを作成する（アーカイブなし）.
	//
	// POST /api/blocks
	CreateBlock(ctx context.Context) (CreateBlockRes, error)
	// CreateDay implements createDay operation.
	//
	// 日エントリを追加する.
	//
	// POST /api/days
	CreateDay(ctx context.Context, req *CreateDayRequest) (CreateDayRes, error)
	// CreateShoppingItem implements createShoppingItem operation.
	//
	// 買い物アイテムを追加する.
	//
	// POST /api/shopping
	CreateShoppingItem(ctx context.Context, req *CreateShoppingItemRequest) (CreateShoppingItemRes, error)
	// DeleteBlock implements deleteBlock operation.
	//
	// ブロックを削除する（最後に作成された未アーカイブのブロックのみ可）.
	//
	// DELETE /api/blocks/{id}
	DeleteBlock(ctx context.Context, params DeleteBlockParams) (DeleteBlockRes, error)
	// DeleteDay implements deleteDay operation.
	//
	// 日エントリを削除する.
	//
	// DELETE /api/days/{id}
	DeleteDay(ctx context.Context, params DeleteDayParams) (DeleteDayRes, error)
	// DeleteShoppingItem implements deleteShoppingItem operation.
	//
	// 買い物アイテムを削除する.
	//
	// DELETE /api/shopping/{id}
	DeleteShoppingItem(ctx context.Context, params DeleteShoppingItemParams) (DeleteShoppingItemRes, error)
	// GetBlock implements getBlock operation.
	//
	// ブロックを取得する.
	//
	// GET /api/blocks/{id}
	GetBlock(ctx context.Context, params GetBlockParams) (GetBlockRes, error)
	// GetCurrentBlock implements getCurrentBlock operation.
	//
	// 現在のブロックを取得する（存在しない場合は自動作成）.
	//
	// GET /api/blocks/current
	GetCurrentBlock(ctx context.Context) (GetCurrentBlockRes, error)
	// GetOIDCConfig implements getOIDCConfig operation.
	//
	// OIDC クライアント設定を取得する（認証不要）.
	//
	// GET /api/oidc-config
	GetOIDCConfig(ctx context.Context) (*OIDCConfig, error)
	// GetUserInfo implements getUserInfo operation.
	//
	// ログイン中のユーザー情報を取得する.
	//
	// GET /api/userinfo
	GetUserInfo(ctx context.Context) (GetUserInfoRes, error)
	// ListBlocks implements listBlocks operation.
	//
	// ブロック一覧を取得する.
	//
	// GET /api/blocks
	ListBlocks(ctx context.Context) (ListBlocksRes, error)
	// ReorderShoppingItems implements reorderShoppingItems operation.
	//
	// 買い物アイテムの順序を変更する.
	//
	// POST /api/shopping/reorder
	ReorderShoppingItems(ctx context.Context, req *ReorderShoppingItemsRequest) (ReorderShoppingItemsRes, error)
	// UnarchiveBlock implements unarchiveBlock operation.
	//
	// 指定ブロックのアーカイブを解除する（アーカイブ済みの中で最新のブロックのみ可）.
	//
	// POST /api/blocks/{id}/unarchive
	UnarchiveBlock(ctx context.Context, params UnarchiveBlockParams) (UnarchiveBlockRes, error)
	// UpdateDay implements updateDay operation.
	//
	// 日エントリを更新する.
	//
	// PUT /api/days/{id}
	UpdateDay(ctx context.Context, req *UpdateDayRequest, params UpdateDayParams) (UpdateDayRes, error)
	// UpdateShoppingItem implements updateShoppingItem operation.
	//
	// 買い物アイテムを更新する.
	//
	// PUT /api/shopping/{id}
	UpdateShoppingItem(ctx context.Context, req *UpdateShoppingItemRequest, params UpdateShoppingItemParams) (UpdateShoppingItemRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
