// Code generated by ogen, DO NOT EDIT.
package api

type ArchiveBlockByIdRes interface {
	archiveBlockByIdRes()
}

type CreateBlockRes interface {
	createBlockRes()
}

type CreateDayRes interface {
	createDayRes()
}

type CreateShoppingItemRes interface {
	createShoppingItemRes()
}

type DeleteBlockRes interface {
	deleteBlockRes()
}

type DeleteDayRes interface {
	deleteDayRes()
}

type DeleteShoppingItemRes interface {
	deleteShoppingItemRes()
}

type GetBlockRes interface {
	getBlockRes()
}

type GetCurrentBlockRes interface {
	getCurrentBlockRes()
}

type GetUserInfoRes interface {
	getUserInfoRes()
}

type ListBlocksRes interface {
	listBlocksRes()
}

type ReorderShoppingItemsRes interface {
	reorderShoppingItemsRes()
}

type UnarchiveBlockRes interface {
	unarchiveBlockRes()
}

type UpdateDayRes interface {
	updateDayRes()
}

type UpdateShoppingItemRes interface {
	updateShoppingItemRes()
}
