// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlcgen

import (
	"context"
)

const archiveBlock = `-- name: ArchiveBlock :exec
UPDATE blocks SET archived_at = datetime('now') WHERE id = ?
`

func (q *Queries) ArchiveBlock(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, archiveBlock, id)
	return err
}

const createBlock = `-- name: CreateBlock :one
INSERT INTO blocks (id) VALUES (?) RETURNING id, created_at, archived_at
`

func (q *Queries) CreateBlock(ctx context.Context, id string) (Block, error) {
	row := q.db.QueryRowContext(ctx, createBlock, id)
	var i Block
	err := row.Scan(&i.ID, &i.CreatedAt, &i.ArchivedAt)
	return i, err
}

const createDayEntry = `-- name: CreateDayEntry :one
INSERT INTO day_entries (id, block_id, date) VALUES (?, ?, ?) RETURNING id, block_id, date, note, lunch, dinner
`

type CreateDayEntryParams struct {
	ID      string `json:"id"`
	BlockID string `json:"block_id"`
	Date    string `json:"date"`
}

func (q *Queries) CreateDayEntry(ctx context.Context, arg CreateDayEntryParams) (DayEntry, error) {
	row := q.db.QueryRowContext(ctx, createDayEntry, arg.ID, arg.BlockID, arg.Date)
	var i DayEntry
	err := row.Scan(
		&i.ID,
		&i.BlockID,
		&i.Date,
		&i.Note,
		&i.Lunch,
		&i.Dinner,
	)
	return i, err
}

const createShoppingItem = `-- name: CreateShoppingItem :one
INSERT INTO shopping_items (id, block_id, name, category, sort_order) VALUES (?, ?, ?, 'food', ?) RETURNING id, block_id, name, category, note, sort_order, checked, created_at
`

type CreateShoppingItemParams struct {
	ID        string `json:"id"`
	BlockID   string `json:"block_id"`
	Name      string `json:"name"`
	SortOrder int64  `json:"sort_order"`
}

func (q *Queries) CreateShoppingItem(ctx context.Context, arg CreateShoppingItemParams) (ShoppingItem, error) {
	row := q.db.QueryRowContext(ctx, createShoppingItem,
		arg.ID,
		arg.BlockID,
		arg.Name,
		arg.SortOrder,
	)
	var i ShoppingItem
	err := row.Scan(
		&i.ID,
		&i.BlockID,
		&i.Name,
		&i.Category,
		&i.Note,
		&i.SortOrder,
		&i.Checked,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBlock = `-- name: DeleteBlock :exec
DELETE FROM blocks WHERE id = ?
`

func (q *Queries) DeleteBlock(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteBlock, id)
	return err
}

const deleteDayEntry = `-- name: DeleteDayEntry :exec
DELETE FROM day_entries WHERE id = ?
`

func (q *Queries) DeleteDayEntry(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDayEntry, id)
	return err
}

const deleteShoppingItem = `-- name: DeleteShoppingItem :exec
DELETE FROM shopping_items WHERE id = ?
`

func (q *Queries) DeleteShoppingItem(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteShoppingItem, id)
	return err
}

const getBlock = `-- name: GetBlock :one
SELECT id, created_at, archived_at FROM blocks WHERE id = ?
`

func (q *Queries) GetBlock(ctx context.Context, id string) (Block, error) {
	row := q.db.QueryRowContext(ctx, getBlock, id)
	var i Block
	err := row.Scan(&i.ID, &i.CreatedAt, &i.ArchivedAt)
	return i, err
}

const getCurrentBlock = `-- name: GetCurrentBlock :one
SELECT id, created_at, archived_at FROM blocks WHERE archived_at IS NULL ORDER BY rowid DESC LIMIT 1
`

func (q *Queries) GetCurrentBlock(ctx context.Context) (Block, error) {
	row := q.db.QueryRowContext(ctx, getCurrentBlock)
	var i Block
	err := row.Scan(&i.ID, &i.CreatedAt, &i.ArchivedAt)
	return i, err
}

const getDayEntriesByBlock = `-- name: GetDayEntriesByBlock :many
SELECT id, block_id, date, note, lunch, dinner FROM day_entries WHERE block_id = ? ORDER BY date ASC
`

func (q *Queries) GetDayEntriesByBlock(ctx context.Context, blockID string) ([]DayEntry, error) {
	rows, err := q.db.QueryContext(ctx, getDayEntriesByBlock, blockID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DayEntry
	for rows.Next() {
		var i DayEntry
		if err := rows.Scan(
			&i.ID,
			&i.BlockID,
			&i.Date,
			&i.Note,
			&i.Lunch,
			&i.Dinner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDayEntry = `-- name: GetDayEntry :one
SELECT id, block_id, date, note, lunch, dinner FROM day_entries WHERE id = ?
`

func (q *Queries) GetDayEntry(ctx context.Context, id string) (DayEntry, error) {
	row := q.db.QueryRowContext(ctx, getDayEntry, id)
	var i DayEntry
	err := row.Scan(
		&i.ID,
		&i.BlockID,
		&i.Date,
		&i.Note,
		&i.Lunch,
		&i.Dinner,
	)
	return i, err
}

const getLatestBlock = `-- name: GetLatestBlock :one
SELECT id, created_at, archived_at FROM blocks ORDER BY rowid DESC LIMIT 1
`

func (q *Queries) GetLatestBlock(ctx context.Context) (Block, error) {
	row := q.db.QueryRowContext(ctx, getLatestBlock)
	var i Block
	err := row.Scan(&i.ID, &i.CreatedAt, &i.ArchivedAt)
	return i, err
}

const getMaxShoppingItemOrder = `-- name: GetMaxShoppingItemOrder :one
SELECT COALESCE(MAX(sort_order), -1) FROM shopping_items WHERE block_id = ?
`

func (q *Queries) GetMaxShoppingItemOrder(ctx context.Context, blockID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxShoppingItemOrder, blockID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getNewestArchivedBlock = `-- name: GetNewestArchivedBlock :one
SELECT id, created_at, archived_at FROM blocks WHERE archived_at IS NOT NULL ORDER BY rowid DESC LIMIT 1
`

func (q *Queries) GetNewestArchivedBlock(ctx context.Context) (Block, error) {
	row := q.db.QueryRowContext(ctx, getNewestArchivedBlock)
	var i Block
	err := row.Scan(&i.ID, &i.CreatedAt, &i.ArchivedAt)
	return i, err
}

const getOldestNonArchivedBlock = `-- name: GetOldestNonArchivedBlock :one
SELECT id, created_at, archived_at FROM blocks WHERE archived_at IS NULL ORDER BY created_at ASC LIMIT 1
`

func (q *Queries) GetOldestNonArchivedBlock(ctx context.Context) (Block, error) {
	row := q.db.QueryRowContext(ctx, getOldestNonArchivedBlock)
	var i Block
	err := row.Scan(&i.ID, &i.CreatedAt, &i.ArchivedAt)
	return i, err
}

const getShoppingItem = `-- name: GetShoppingItem :one
SELECT id, block_id, name, category, note, sort_order, checked, created_at FROM shopping_items WHERE id = ?
`

func (q *Queries) GetShoppingItem(ctx context.Context, id string) (ShoppingItem, error) {
	row := q.db.QueryRowContext(ctx, getShoppingItem, id)
	var i ShoppingItem
	err := row.Scan(
		&i.ID,
		&i.BlockID,
		&i.Name,
		&i.Category,
		&i.Note,
		&i.SortOrder,
		&i.Checked,
		&i.CreatedAt,
	)
	return i, err
}

const getShoppingItemsByBlock = `-- name: GetShoppingItemsByBlock :many
SELECT id, block_id, name, category, note, sort_order, checked, created_at FROM shopping_items WHERE block_id = ? ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) GetShoppingItemsByBlock(ctx context.Context, blockID string) ([]ShoppingItem, error) {
	rows, err := q.db.QueryContext(ctx, getShoppingItemsByBlock, blockID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShoppingItem
	for rows.Next() {
		var i ShoppingItem
		if err := rows.Scan(
			&i.ID,
			&i.BlockID,
			&i.Name,
			&i.Category,
			&i.Note,
			&i.SortOrder,
			&i.Checked,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlocks = `-- name: ListBlocks :many
SELECT id, created_at, archived_at FROM blocks ORDER BY rowid ASC
`

func (q *Queries) ListBlocks(ctx context.Context) ([]Block, error) {
	rows, err := q.db.QueryContext(ctx, listBlocks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Block
	for rows.Next() {
		var i Block
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.ArchivedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unarchiveBlock = `-- name: UnarchiveBlock :exec
UPDATE blocks SET archived_at = NULL WHERE id = ?
`

func (q *Queries) UnarchiveBlock(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, unarchiveBlock, id)
	return err
}

const updateDayEntry = `-- name: UpdateDayEntry :one
UPDATE day_entries SET note = ?, lunch = ?, dinner = ? WHERE id = ? RETURNING id, block_id, date, note, lunch, dinner
`

type UpdateDayEntryParams struct {
	Note   *string `json:"note"`
	Lunch  *string `json:"lunch"`
	Dinner *string `json:"dinner"`
	ID     string  `json:"id"`
}

func (q *Queries) UpdateDayEntry(ctx context.Context, arg UpdateDayEntryParams) (DayEntry, error) {
	row := q.db.QueryRowContext(ctx, updateDayEntry,
		arg.Note,
		arg.Lunch,
		arg.Dinner,
		arg.ID,
	)
	var i DayEntry
	err := row.Scan(
		&i.ID,
		&i.BlockID,
		&i.Date,
		&i.Note,
		&i.Lunch,
		&i.Dinner,
	)
	return i, err
}

const updateShoppingItem = `-- name: UpdateShoppingItem :one
UPDATE shopping_items SET name = ?, checked = ?, note = ? WHERE id = ? RETURNING id, block_id, name, category, note, sort_order, checked, created_at
`

type UpdateShoppingItemParams struct {
	Name    string  `json:"name"`
	Checked int64   `json:"checked"`
	Note    *string `json:"note"`
	ID      string  `json:"id"`
}

func (q *Queries) UpdateShoppingItem(ctx context.Context, arg UpdateShoppingItemParams) (ShoppingItem, error) {
	row := q.db.QueryRowContext(ctx, updateShoppingItem,
		arg.Name,
		arg.Checked,
		arg.Note,
		arg.ID,
	)
	var i ShoppingItem
	err := row.Scan(
		&i.ID,
		&i.BlockID,
		&i.Name,
		&i.Category,
		&i.Note,
		&i.SortOrder,
		&i.Checked,
		&i.CreatedAt,
	)
	return i, err
}

const updateShoppingItemOrder = `-- name: UpdateShoppingItemOrder :exec
UPDATE shopping_items SET sort_order = ? WHERE id = ?
`

type UpdateShoppingItemOrderParams struct {
	SortOrder int64  `json:"sort_order"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateShoppingItemOrder(ctx context.Context, arg UpdateShoppingItemOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateShoppingItemOrder, arg.SortOrder, arg.ID)
	return err
}
